Rewrite spells
jcderry5/step-strikers pull request #88
Opened 2023-03-21 18:05 UTC by jcderry5

2023-03-23 16:10 UTC, alekhyaku approved these changes
lgtm!

2023-03-23 16:36 UTC, KellyPSun requested changes
Some of the spells are wonky. I only tried shield and invisible but both crashed. Fight is still perfectly fine so I think it's a problem with spells.

2023-03-23 17:33 UTC, jcderry5 commented on step-strikers-app/step-strikers-app/Battle Screens/BattleSelectActionViewController.swift
> +            localCharacter.fight(rollValue: rollValue!)
I have a list on a sticky note at home of 4 spells that do not move on past endTurn after casting them. I know those 2 are one of them. I thought it was an issue with the server not being on though so I just ignored it. I'll go back and figure out why this is happening!

2023-03-24 16:50 UTC, KellyPSun approved these changes

2023-03-24 17:46 UTC, merged